@startuml  

start  
:Gebruiker selecteert optie om gegevens uit CSV te lezen;  
if (Geldig CSV-bestand en toegang tot de applicatie) then  
  :Systeem laadt en verwerkt gegevens uit CSV-bestand;  
  :Gegevens importeren in de applicatie;  
  :Systeem geeft bevestiging van succesvolle import;  
else  
  :Foutmelding weergeven;  
endif  
  
stop  

@enduml  