@startuml

start  
:Gebruiker voert naam en afstand van persoon in;  
if (Persoon bestaat niet in database) then  
  :Gegevens opslaan in database;  
  :Bevestiging weergeven van succesvolle opslag;  
else  
  :Melding weergeven dat persoon al bestaat;  
endif  
  
stop  

@enduml
