
@startuml
package "P1 Eindapplicatie" {
  [Klaskompas] --> [Persoonsbeheer]
  [Klaskompas] --> [Hobbybeheer]
  [Klaskompas] --> [Visualisatie]
  [Persoonsbeheer] --> [Database]
  [Hobbybeheer] --> [Database]
  [Visualisatie] --> [Database]
}
@enduml
