
@startuml
package "P1 Eindapplicatie" {
  [Klaskompas] --> [Person Management]
  [Klaskompas] --> [Hobby Management]
  [Klaskompas] --> [Visualisation]
  [Person Management] --> [Database]
  [Hobby Management] --> [Database]
}
@enduml
