@startuml KlasKompas_PDM
'configuration
hide circle
hide attributes

entity persoon {
    naam : VARCHAR(50) <<PK>>
    afstand : NUMERIC(3,1)
}

entity hobby {
    naam : VARCHAR(50) <<PK,FK>>
    hobby : VARCHAR(75) <<PK>>
}

persoon <- hobby

@enduml