@startuml KlasKompas_PDM
'configuration
hide circle

entity persoon {
    naam : TEXT NN <<PK>>
    afstand : NUMERIC(3,1) NN
}

entity hobby {
    naam : TEXT NN <<PK,FK>>
    hobby : TEXT NN <<PK>>
}

persoon <- hobby

@enduml